services:
  blog:
    image: devkyu96/blog:v1
    container_name: blog-nestjs
    restart: always
    environment:
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DB: "${MYSQL_DB_DEV}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${DB_HOST}:${DB_PORT}/${MYSQL_DB_DEV}"
    ports:
      - "3000:3000"
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  certs:
  html:
  letsencrypt:
  acme:

      