services:
  blog:
    image: devkyu96/blog:v1
    container_name: blog-nestjs
    restart: always
    environment:
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DB: "${MYSQL_DB}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${DB_HOST}:${DB_PORT}/${MYSQL_DB}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
      JWT_EXPIRES_IN: "${JWT_EXPIRES_IN}"
      LETSENCRYPT_HOST: "devkyu96.site"
      LETSENCRYPT_EMAIL: devkyu96@gmail.com
    ports:
      - "3000:3000"
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  certs:
  html:
  letsencrypt:
  acme:

      