services:
  blog:
    image: devkyu96/blog:v1
    container_name: blog-nestjs
    restart: always
    environment:
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DB: "${MYSQL_DB}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${DB_HOST}:${DB_PORT}/${MYSQL_DB}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
      JWT_EXPIRES_IN: "${JWT_EXPIRES_IN}"
      LETSENCRYPT_HOST: "${LETSENCRYPT_HOST}"
      LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
      VIRTUAL_HOST: "${VIRTUAL_HOST}"
      VUE_URL: "${VUE_URL}"
      VUE_TEST_URL: "${VUE_TEST_URL}"
    ports:
      - "3000:3000"
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  certs:
  html:
  letsencrypt:
  acme:

      