version: '3'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${{ secret.MYSQL_PASSWORD }}
      MYSQL_DATABASE: blog
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
